const Images = {
  logo: require("../../assets/images/logo.png"),
  warming: require("../../assets/images/warming.png"),
  search: require("../../assets/images/search.png"),
  sort: require("../../assets/images/sort.png"),
  right: require("../../assets/images/right.png"),
  down: require("../../assets/images/down.png"),
  Ellipse: require("../../assets/images/Ellipse.png"),
  graystar: require("../../assets/images/graystar.png"),
  citi: require("../../assets/images/citi.png"),
  plus: require("../../assets/images/plus.png"),
  featureLock: require("../../assets/images/featureLock.png"),
  plusCircle: require("../../assets/images/plusCircle.png"),
  checkbox: require("../../assets/images/checkbox.png"),
  leave: require("../../assets/images/leave.png"),
  greentick: require("../../assets/images/greentick.png"),
  arrowUp: require("../../assets/images/arrowUp.png"),
  downarrowblue: require("../../assets/images/downarrowblue.png"),
  filter: require("../../assets/images/filter.png"),
  forwardArrow: require("../../assets/images/forwardArrow.png"),
  iPhone: require("../../assets/images/iPhone.png"),
  halfcircle: require("../../assets/images/halfcircle.png"),
  backgroundIllustration: require("../../assets/images/bg_illustration.png"),
  illustrations1: require("../../assets/images/illustrations1.png"),
  illustrations2: require("../../assets/images/illustrations2.png"),
  illustrations3: require("../../assets/images/illustrations3.png"),
  arrowRight1: require("../../assets/images/arrowRightIcon.png"),
  miniLogo: require("../../assets/images/miniLogo.png"),
  signUpmodalIcon: require("../../assets/images/signUpModalIcon.png"),
  arrowBackIcon: require("../../assets/images/arrowBackIcon.png"),
  googleIcon: require("../../assets/images/googleIcon.png"),
  signupErrorIcon: require("../../assets/images/signupErrorIcon.png"),
  tickIcon: require("../../assets/images/tickIcon.png"),
  emailVerificationIcon: require("../../assets/images/verificationEmailIcon.png"),
}

export default Images
